apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-prom
  labels:
    app: flask-prom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-prom
  template:
    metadata:
      labels:
        app: flask-prom
    spec:
      containers:
        - name: app
          image: flask-prom-demo
          ports:
            - containerPort: 5000

