apiVersion: v1
kind: Service
metadata:
  name: flask-prom
  labels:
    app: flask-prom
spec:
  selector:
    app: flask-prom
  ports:
    - name: http   # ⬅️ 这个名字极其重要
      port: 80
      targetPort: 5000

